//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTools.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VTools.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a file.
        /// </summary>
        public static string ChooseFile_Button_Content {
            get {
                return ResourceManager.GetString("ChooseFile_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearLogs_Button_Content {
            get {
                return ResourceManager.GetString("ClearLogs_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string CopyLogs_Button_Content {
            get {
                return ResourceManager.GetString("CopyLogs_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cutting.
        /// </summary>
        public static string Cut_Expander_Header {
            get {
                return ResourceManager.GetString("Cut_Expander_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut video.
        /// </summary>
        public static string CutVideo_TextBlock {
            get {
                return ResourceManager.GetString("CutVideo_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories.
        /// </summary>
        public static string Directories_TextBlock {
            get {
                return ResourceManager.GetString("Directories_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download_Button_Content {
            get {
                return ResourceManager.GetString("Download_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloader.
        /// </summary>
        public static string Downloader_Tab_Header {
            get {
                return ResourceManager.GetString("Downloader_Tab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download FFmpeg.
        /// </summary>
        public static string DownloadFFMPEG_Button_Content {
            get {
                return ResourceManager.GetString("DownloadFFMPEG_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download yt-dlp.
        /// </summary>
        public static string DownloadYTDLP_Button_Content {
            get {
                return ResourceManager.GetString("DownloadYTDLP_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit_Button_Content {
            get {
                return ResourceManager.GetString("Edit_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string Editor_Tab_Header {
            get {
                return ResourceManager.GetString("Editor_Tab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End_TextBlock {
            get {
                return ResourceManager.GetString("End_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External tools.
        /// </summary>
        public static string ExternalTools_TextBlock {
            get {
                return ResourceManager.GetString("ExternalTools_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Format_TextBlock {
            get {
                return ResourceManager.GetString("Format_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string Logs_Expander_Header {
            get {
                return ResourceManager.GetString("Logs_Expander_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file chosen.
        /// </summary>
        public static string MediaPath_TextBox_Watermark {
            get {
                return ResourceManager.GetString("MediaPath_TextBox_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the URL of a media file.
        /// </summary>
        public static string MediaURL_TextBox_Watermark {
            get {
                return ResourceManager.GetString("MediaURL_TextBox_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open app directory.
        /// </summary>
        public static string OpenAppDirectory_Button_Content {
            get {
                return ResourceManager.GetString("OpenAppDirectory_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter output file name.
        /// </summary>
        public static string OutputFileName_TextBox_Watermark {
            get {
                return ResourceManager.GetString("OutputFileName_TextBox_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Tab_Header {
            get {
                return ResourceManager.GetString("Settings_Tab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start_TextBlock {
            get {
                return ResourceManager.GetString("Start_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User interface.
        /// </summary>
        public static string UI_TextBlock {
            get {
                return ResourceManager.GetString("UI_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Language.
        /// </summary>
        public static string UILanguage_TextBlock {
            get {
                return ResourceManager.GetString("UILanguage_TextBlock", resourceCulture);
            }
        }
    }
}
