//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTools.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VTools.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this app.
        /// </summary>
        public static string AboutThisApp_TextBlock {
            get {
                return ResourceManager.GetString("AboutThisApp_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App folder.
        /// </summary>
        public static string AppFolder_TextBlock {
            get {
                return ResourceManager.GetString("AppFolder_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cutting.
        /// </summary>
        public static string Cut_Expander_Header {
            get {
                return ResourceManager.GetString("Cut_Expander_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Cut_TextBlock {
            get {
                return ResourceManager.GetString("Cut_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloader.
        /// </summary>
        public static string Downloader_Expander_Header {
            get {
                return ResourceManager.GetString("Downloader_Expander_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloader.
        /// </summary>
        public static string Downloader_Tab_Header {
            get {
                return ResourceManager.GetString("Downloader_Tab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download FFmpeg and FFprobe.
        /// </summary>
        public static string DownloadFFmpeg_Button_Content {
            get {
                return ResourceManager.GetString("DownloadFFmpeg_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download path.
        /// </summary>
        public static string DownloadPath_TextBlock {
            get {
                return ResourceManager.GetString("DownloadPath_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download yt-dlp.
        /// </summary>
        public static string DownloadYTDLP_Button_Content {
            get {
                return ResourceManager.GetString("DownloadYTDLP_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string Editor_Tab_Header {
            get {
                return ResourceManager.GetString("Editor_Tab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End_TextBlock {
            get {
                return ResourceManager.GetString("End_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable path.
        /// </summary>
        public static string ExecutablePath_TextBlock {
            get {
                return ResourceManager.GetString("ExecutablePath_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string Extension_TextBlock {
            get {
                return ResourceManager.GetString("Extension_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External tools.
        /// </summary>
        public static string ExternalTools_TextBlock {
            get {
                return ResourceManager.GetString("ExternalTools_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg &amp; FFprobe.
        /// </summary>
        public static string FFmpegAndFFprobe_Expander_Header {
            get {
                return ResourceManager.GetString("FFmpegAndFFprobe_Expander_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg executable path.
        /// </summary>
        public static string FFmpegExecutablePath_TextBlock {
            get {
                return ResourceManager.GetString("FFmpegExecutablePath_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFprobe executable path.
        /// </summary>
        public static string FFprobeExecutablePath_TextBlock {
            get {
                return ResourceManager.GetString("FFprobeExecutablePath_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Format_Expander_Header {
            get {
                return ResourceManager.GetString("Format_Expander_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General_TextBlock {
            get {
                return ResourceManager.GetString("General_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language_TextBlock {
            get {
                return ResourceManager.GetString("Language_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string Logs_Expander_Header {
            get {
                return ResourceManager.GetString("Logs_Expander_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file chosen.
        /// </summary>
        public static string MediaPath_TextBox_Watermark {
            get {
                return ResourceManager.GetString("MediaPath_TextBox_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the URL of a media file.
        /// </summary>
        public static string MediaURL_TextBox_Watermark {
            get {
                return ResourceManager.GetString("MediaURL_TextBox_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Expander_Header {
            get {
                return ResourceManager.GetString("Options_Expander_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter output file name.
        /// </summary>
        public static string OutputFileName_TextBox_Watermark {
            get {
                return ResourceManager.GetString("OutputFileName_TextBox_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub repository.
        /// </summary>
        public static string Repository_Button_Content {
            get {
                return ResourceManager.GetString("Repository_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Tab_Header {
            get {
                return ResourceManager.GetString("Settings_Tab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start_TextBlock {
            get {
                return ResourceManager.GetString("Start_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update yt-dlp.
        /// </summary>
        public static string UpdateYTDLP_Button_Content {
            get {
                return ResourceManager.GetString("UpdateYTDLP_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User interface.
        /// </summary>
        public static string UserInterface_Expander_Header {
            get {
                return ResourceManager.GetString("UserInterface_Expander_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yt-dlp.
        /// </summary>
        public static string YTDLP_Expander_Header {
            get {
                return ResourceManager.GetString("YTDLP_Expander_Header", resourceCulture);
            }
        }
    }
}
